### PR TITLE
chore: update tailwind module to 4

### PR DESCRIPTION
**Pull request by dennistruemper**
Hi Dillon, just tried html-to-elm for tailwind this morning after replaying elm-radio 27. I got errors for colors. Because:

original tailwind: bg_gray_500
tailwind modules "old": Tw.bg_gray_500
tailwind modules current (4.0.1): Tw.bg_color Tw.gray_500 (with Tw import of Theme and Utilities)

The second commit is the one with code changes. 

I though about colors with 2 and 3 digits (50, 100, 200, etc) and 3 without shades (black, white, transparent) so maybe some cases should be added (primary, secondary, ...), or the solution should be based on the wirst part (bg_, text_ , etc)?

Also "Tw." is not hard coded (any more), but I use the Config I found.

Code is not nice to look at, but at least it works for every color in ete tests. 

Maybe there should be an option to select the version, because this was a breaking change, html-to-elm would be bound to tailwind-modules 4.0.1 right now. I do not know how many users are using older tailwind-modules right now with html-to-elm.

Quickfix would be to provide a Regex to replace generated code with tailwind-modules 4.0.1 code. 
VsCode example: search = Tw\.(\w+)_(\w+_\d{2,3}|black|white|transparent) replace = $1_color Tw.$2

Let me know what you want to do with this and if I can support,
Dennis

### CODE REVIEW

**Comment by dillonkearns** [comment]
Hello Dennis,

Thanks so much for working on this!

In the new `elm-tailwind-modules`, we did the color detection based on the actual resolved colors from the Tailwind config. This works well for the CLI since we have access to the config, so this is a pretty robust way to handle it (the implementation details aren't too important, but here's the code if you're curious: https://github.com/matheus23/elm-tailwind-modules/blob/518b7e608d8d5a36e3b837180cca7d1bc16d0dd1/src/parser.ts#L345-L453).

But this does indeed present a challenge in the case of html-to-elm because we don't have access to the specific Tailwind config and therefore we can't resolve the list of colors.

My first thought here is that we could have the following options:

1) Default should work out of the box with the standard Tailwind config. 99% of the time I imagine people are copy-pasting Tailwind examples that use the standard palette (like from the Tailwind site, or Tailwind UI).
2) Could provide some configuration for more advanced use cases. That could either take the form of a Regex that the user can supply (more concise), or a list of color values (could get tedious to enter that for all possible combinations, so doesn't seem too feasible).

What do you think about that idea from a user-facing point of view?

Regarding your Regex here:

https://github.com/dillonkearns/elm-review-html-to-elm/blob/705589495ab71fcfe656c4ec34505482754d8d96/src/TailwindClass.elm#L113

I'm not sure off the top of my head if this covers all of the possible colors from the default Tailwind 3 config, is there a way we could check on that?

> Maybe there should be an option to select the version, because this was a breaking change, html-to-elm would be bound to tailwind-modules 4.0.1 right now.

I've considered this as well. I think one simple option that would work pretty well would be to include a link to the old version on the site. Netlify lets you link to a snapshot of old versions of the site, so people can still access the exact version that is in production right now from this URL: https://62601eadf9b3d000098c8b05--html-to-elm-tailwind.netlify.app/. So I think that it would be pretty reasonable to have a link to that old version for anyone who hasn't upgraded, since over time that will become less of an issue.

Let me know your thoughts, and thanks again!

**Comment by dillonkearns** [comment]
And regarding the timing for (1) and (2), I just wanted to think those details through a little bit, but I think it would be reasonable to ship this PR once we're convinced that (1) is solid, then address (2) separately down the line.

**Comment by dennistruemper** [comment]
Hi, I just started to listen to "Why we care about Elm", so I totally understand the 99% might not be enough ;-) 

Just hat a look at https://tailwindcss.com/docs/background-color. This should be a complete list of tailwind default colors? So the patters of context-color-number are all hit by regex, but "inherit" and "current" are missing. I will add those.

Snapshot with current version is a nice idea.  So no backports to the old version I guess ;-) 

For real guarantee the tailwind config is needed, so there has to be an "upload" option, but just to the website, no server involved. Maybe a feature for later on. Custom colors with shades will work too (bg_customcolor_500), it ist just the named colors like "primary" not working without config knowledeg.
Other option is a field to paste custom color names with local storage persistence, so you do not have to do it every time?

I'm glad I can give something back, the elm community introduced me to so many cool ideas <3 I care about elm too, but not using it that much to be honest. Maybe next year, by day I am a backend developer ;-)

**Comment by dennistruemper** [comment]
Oh and what was really cool, I was able to use the version from this PR with the netlify deploy link. So I could use it without waiting for an official release ^^

**Comment by dillonkearns** [comment]
> Hi, I just started to listen to "Why we care about Elm", so I totally understand the 99% might not be enough ;-)

Indeed, getting those trustworthy tools is worth the extra effort for sure!

> Just hat a look at https://tailwindcss.com/docs/background-color. This should be a complete list of tailwind default colors? So the patters of context-color-number are all hit by regex, but "inherit" and "current" are missing. I will add those.

Prefect, thank you for checking on that!

> For real guarantee the tailwind config is needed, so there has to be an "upload" option, but just to the website, no server involved. Maybe a feature for later on. Custom colors with shades will work too (bg_customcolor_500), it ist just the named colors like "primary" not working without config knowledeg.
> Other option is a field to paste custom color names with local storage persistence, so you do not have to do it every time?

Yeah, that would be good to explore more in-depth in another GitHub Issue or PR. Thanks for helping me think through that! Having a way to upload a Tailwind config is an interesting idea. My first thought is that just allowing the user to supplying a Regex may be good enough, so I'm inclined to start there, but something to explore.

> Other option is a field to paste custom color names with local storage persistence, so you do not have to do it every time?

The config is already persisted in local storage! Right now the config is the aliases list, exposing lists, and use tailwind boolean. But if we added an option for setting a Regex pattern for colors that would get persisted in the settings as well.

By the way, I went ahead and pushed up a change that adds a special config for `import Tailwind.Theme`, so that can be configured now, too. So at this point I think this is looking ready to merge!

Thanks again for submitting the PR 🙏

**Pull request merged**
